In [1]:
import time
import pandas as pd
import warnings
import feather
warnings.filterwarnings('ignore')
from pandas.api.types import is_string_dtype
from pandas.api.types import is_numeric_dtype
pd.set_option('display.max_columns', None)

In [3]:
DF_09 = pd.read_feather('2009/2009_FULL.feather')
DF_10 = pd.read_feather('2010/2010_FULL.feather')
DF_11 = pd.read_feather('2011/2011_FULL.feather')
DF_12 = pd.read_feather('2012/2012_FULL.feather')
DF_13 = pd.read_feather('2013/2013_FULL.feather')
DF_14 = pd.read_feather('2014/2014_FULL.feather')
DF_15 = pd.read_feather('2015/2015_FULL.feather')
DF_16 = pd.read_feather('2016/2016_FULL.feather')
DF_17 = pd.read_feather('2017/2017_FULL.feather')
DF_18 = pd.read_feather('2018/2018_FULL.feather')

In [4]:
DF = pd.concat([DF_09,DF_10,DF_11,DF_12,DF_13,DF_14,DF_15,DF_16,DF_17,DF_18])

In [8]:
DF.head(2)

,CO_ANO,CO_ESCOLA,CO_INSCRICAO,NU_IDADE,TP_COR_RACA,NU_NOTA_CN,NU_NOTA_CH,NU_NOTA_LC,NU_NOTA_MT,NU_NOTA_REDACAO,EDU_PAI,EDU_MAE,OCU_MAE,OCU_PAI,QT_PESSOAS_CASA,RENDA_MENSAL,QT_CARRO,QT_MAQUINA_LAVAR,QT_TELEVISAO_CORES,QT_TV_ASSINATURA,QT_CELULAR,QT_TELEFONE_FIXO,QT_COMPUTADOR,QT_INTERNET,QT_CURSOU_EM,TP_ESCOLA_EF,QT_CURSOU_EF,TP_SEXO,TITULACAO,CO_DEPENDENCIA_ADM,CO_UF,CO_MUNICIPIO,IN_AGUA_INEXISTENTE,IN_ESGOTO_INEXISTENTE,IN_ENERGIA_INEXISTENTE,IN_LABORATORIO_INFORMATICA,IN_LABORATORIO_CIENCIAS,IN_SALA_ATENDIMENTO_ESPECIAL,IN_QUADRA_ESPORTES,IN_BIBLIOTECA,IN_SALA_LEITURA,IN_BANHEIRO_FORA_PREDIO,IN_BANHEIRO_PNE,IN_DEPENDENCIAS_PNE,QT_SALAS_UTILIZADAS,QT_EQUIP_TV,QT_EQUIP_DVD,QT_EQUIP_COPIADORA,QT_EQUIP_IMPRESSORA,QT_COMP_ALUNO,IN_INTERNET,IN_BANDA_LARGA,QT_FUNCIONARIOS,IN_ALIMENTACAO,NU_NOTA_GERAL,TARGET,TP_PRESENCA_CN,TP_PRESENCA_CH,TP_PRESENCA_LC,TP_PRESENCA_MT,TP_LINGUA,QT_BANHEIRO,QT_FREEZER,QT_ASPIRADOR,QT_TV _ASSINATURA,IN_INTERNET_x,TP_STATUS_REDACAO,COD_MUNICIPIO,IN_QUADRA_ESPORTES_COBERTA,IN_QUADRA_ESPORTES_DESCOBERTA,IN_INTERNET_y,IN_BANHEIRO_CHUVEIRO,IN_REFEITORIO,IN_DESPENSA,IN_ALMOXARIFADO,IN_AUDITORIO,IN_PATIO_COBERTO,IN_PATIO_DESCOBERTO,IN_AREA_VERDE,QT_EQUIP_SOM,QT_EQUIP_MULTIMIDIA,QT_EQUIP_FOTO,NUM_FUNCIONARIOS,ID_ALIMENTACAO,TP_NACIONALIDADE,IN_TREINEIRO,QT_MAQUINA_SECAR,QT_MICRO-ONDAS,QT_EQUIP_IMPRESSORA_MULT,QT_FUNCIOARIOS
0,2009,33052182.0,1.000013e+11,19.0,A,409.0,323.0,377.0,360.0,475.0,1,4,3,9,2,1,3.0,0.0,0,3.0,2,0,0,0.0,1.0,A,B,0.0,0.074074,2,33,3305752.0,0.0,0.0,0.0,1.0,0.0,0.0,1,1.0,0.0,0.0,0.0,0.0,16.0,1.0,1.0,1.0,1.0,10.0,1,1.0,110.0,1,388.799988,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2009,33044384.0,1.000016e+11,19.0,A,476.0,434.0,433.0,427.0,525.0,1,4,3,9,2,1,3.0,0.0,0,3.0,2,0,0,0.0,1.0,A,B,0.0,0.142857,2,33,3304300.0,0.0,0.0,0.0,1.0,0.0,1.0,1,1.0,0.0,0.0,0.0,0.0,10.0,1.0,1.0,1.0,1.0,8.0,1,1.0,91.0,1,459.000000,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [24]:
DF.to_csv('ALL_YEATS.csv')